apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-uploads-pvc
  namespace: maya-geo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-app
  namespace: maya-geo
  labels:
    app: strapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi-app
  template:
    metadata:
      labels:
        app: strapi-app
    spec:
      containers:
        - name: strapi-app
          image: ghcr.io/idoGit1/geo-course-strapi:latest
          ports:
            - containerPort: 1337
          env:
            - name: NODE_ENV
              value: "production"
            - name: APP_KEYS
              value: "toBeModified1,toBeModified2"
            - name: API_TOKEN_SALT
              value: "someRandomSalt"
            - name: ADMIN_JWT_SECRET
              value: "someAdminJwtSecret"
            - name: TRANSFER_TOKEN_SALT
              value: "someTransferTokenSalt"
            - name: JWT_SECRET
              value: "someJwtSecret"
          volumeMounts:
            - name: uploads-storage
              mountPath: /opt/app/public/uploads
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: strapi-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  namespace: maya-geo
spec:
  type: ClusterIP
  ports:
    - port: 1337
      targetPort: 1337
  selector:
    app: strapi-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strapi-ingress
  namespace: maya-geo
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - strapi.84.13.64.198.sslip.io
      secretName: strapi-app-tls
  rules:
    - host: strapi.84.13.64.198.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strapi-service
                port:
                  number: 1337