apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: maya-geo
  labels:
    app: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: strapi
          image: ghcr.io/idogit1/geo-course-strapi:latest
          ports:
            - containerPort: 1337
          envFrom:
            - configMapRef:
                name: strapi-config
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: strapi-svc
  namespace: maya-geo
spec:
  type: ClusterIP
  ports:
    - port: 1337
      targetPort: 1337
  selector:
    app: strapi